### ISSUE TITLE
Cannot invoke "com.google.gson.JsonElement.getAsString()" error

### ISSUE THREAD

**Issue by RedPxnda** [AFunProject/Reputation#1]
After attempting to create a faction, the reload fails and throws an error.
**data/reputation/factions/villager.json:**
`{
    "name": "villager",
    "default_reputation": 15,
    "lower_reputation_bound": -50,
    "upper_reputation_bound": 50,
    "weighted_murder": 10,
    "weighted_looting": 5,
    "weighted_fleeing": 2,
    "members": [
        "minecraft:villager",
        "guardvillagers:guard",
        "minecraft:iron_golem",
        "minecraft:wandering_trader"
    ],
    "enemies": []
}`
**data/reputation/ai.json:**
`{
    "passive_fleeing": [
         "minecraft:villager"
    ],
    "hostile": [],
    "passive_neutral": [],
    "passive_good": [],
    "hostile_fleeing": [
         "minecraft:pillager"
    ]
}`

**error in latest.log:** 
https://hastebin.com/arikoxisuf.md

**Comment by TheComputerizer** [comment]
oh yeah my bad the example is a bit outdated. The categories for the AI file are `passive_fleeing`, `hostile`, `passive`, `injured_fleeing`, and `trading`. The faction file also needs a `currency` item
