### ISSUE TITLE
Skeletons burn in the Nether...really weird stuff

### ISSUE THREAD

**Issue by Cixon** [AFunProject/Reputation#11]
Idk if this is derived from DawnCraft but I'd like to know if this is a bug or a feature. If it's a feature may I please remove it and if it's a bug, please fix it.

**Comment by TheComputerizer** [comment]
This has nothing to do with the Reputation mod

**Comment by Cixon** [comment]
So then why does it occur when reputation is installed? I disable it via Curseforge launcher and the skeletons no longer burn in the Nether.

**Comment by TheComputerizer** [comment]
Ok so I double checked the source and you are right that is in the mod for some reason. I suspect it may have been from the previous dev who set up the mod before I started developing it because that isn't something I put in or should be in at all. It will be removed with the next update

**Comment by Cixon** [comment]
I appreciate this! No worries, thank you for applying a fix

**Comment by TheComputerizer** [comment]
Fixed in 1.0.0
