### ISSUE TITLE
Suggestion: compat with Minecraft Comes Alive Reborn

### ISSUE THREAD

**Issue by pantsguyapp** [AFunProject/Reputation#14]
Idk if this mod's housing requirement mechanic also expand to other villager based mobs such as MCA villagers who share the code with vanilla villagers.

Also does this mod allow MCA villagers to have chaf bubbles?

**Comment by TheComputerizer** [comment]
Reputation doesn't do anything with housing requirements. Any living entity can have chat bubbles as long as they are assigned to at least 1 faction

Also as this is a place to post issues, questions are better asked in the discord server linked on the CF page or via a CF comment with the legacy site

**Comment by TheComputerizer** [comment]
As it turns out I had forgotten to add the hyperlink to the little Discord x online image at the top of the page. This has been fixed, thanks for pointing it out
