### ISSUE TITLE
Please remove the memory leak in WorldEvents 

### ISSUE THREAD

**Issue by GotoFinal** [AFunProject/Reputation#15]
https://github.com/AFunProject/Reputation/blob/main/src/main/java/mods/thecomputerizer/reputation/common/event/WorldEvents.java#L52C45-L52C52

Players are never removed form the list, causing to consume GB of memory over few hours.

**Comment by TheComputerizer** [comment]
This is a good find and will be in 1.0.0

**Comment by TheComputerizer** [comment]
Should be fixed in 1.0.0. Feel free it open another issue if there are still problems
