### ISSUE TITLE
[Question] About porting to Forge 1.16.5

### ISSUE THREAD

**Issue by KLjiana** [AFunProject/Reputation#16]
I'm interested in this mod and want to play it in 1.16.5Forge. But I don't know Java. As an author, can you port it to 1.16.5Forge? Thanks.

**Comment by TheComputerizer** [comment]
Yeah it's on the to-do after 1.0.0 is released which is getting pretty close

**Comment by KLjiana** [comment]
Okay, thanks for your reply, I'm looking forward to that time
