### ISSUE TITLE
Error in selected datapacks with no error log and no datapacks

### ISSUE THREAD

**Issue by RedPxnda** [AFunProject/Reputation#2]
Whenever trying to load the world, the game says that there's an error in a loaded datapack. Problem is, I don't have any datapacks loaded. (at some point I did but disabled them to test this) Removing the mod fixes this issue.
Creating a new instance with none of the mods seemed to fix it, but I really don't want to have to go through every single mod to find the one causing issues.

There is only 1 related thing in the logs, but I doubt that has anything to do with this issue:
https://hastebin.com/soharotagu.css

**Comment by TheComputerizer** [comment]
I'm going to need a full log with the error in it after failing load

**Comment by TheComputerizer** [comment]
The hastebin link seems to have expired. Do you still have a copy of the full log? If not I will have to close the issue

**Comment by TheComputerizer** [comment]
This has probably either been fixed or is not an issue anymore
