### ISSUE TITLE
Apotheosis crafting recipes are being removed with reputation installed

### ISSUE THREAD

**Issue by Kogexus** [AFunProject/Reputation#3]
I've noticed from the logs that some apotheosis recipes are being removed when reputation is present. Here are the logs when loading a new world with only reputation and apotheosis (with its dependencies) are loaded. 
[latest.log](https://github.com/AFunProject/Reputation/files/9682158/latest.log)

**Comment by TheComputerizer** [comment]
Thats a bit strange I will have to see how apotheosis is registering its recipes

**Comment by TheComputerizer** [comment]
This should be fixed in 0.9.3
