### ISSUE TITLE
[Performance] Check the sight of factions

### ISSUE THREAD

**Issue by SettingDust** [AFunProject/Reputation#6]
https://spark.lucko.me/Z1UhCookSc

https://github.com/AFunProject/Reputation/blob/main/src/main/java/mods/thecomputerizer/reputation/util/HelperMethods.java#L179
Need perf.
Such as don't use `matches`.
Need look into it

**Comment by SettingDust** [comment]
https://spark.lucko.me/0IdVbNZ0FE

**Comment by TheComputerizer** [comment]
It should be a lot better in 1.0.0 now, but feel free to open another issue if there are performance still problems
