### ISSUE TITLE
[Suggestion] Visualized Player's Reputation

### ISSUE THREAD

**Issue by VVVHY** [AFunProject/Reputation#7]
There's few ways for players to know what their reputation are and which past actions affect their reputation. Maybe it could be more friendly to add visual reputation interface or a tool to check the reputation, and keep a record about the past actions which make an influence to the player's reputation.

**Comment by ZeekDaGeek** [comment]
When gaining or losing reputation it would be nice if there was a visual notification somewhere letting you know, or possibly audio.

Right now it's very ambiguous, does opening a chest only while a villager's looking at you reduce reputation? Does any container count or only vanilla chests and barrels? Is it possible to be a sneaky thief and steal when a villager is far away or is it any chest in town? If I put a chest down and open it up and close it does it do anything to my reputation, am I being penalized for building too close to town?

A lot of that could be cleared up with feedback.

**Comment by TheComputerizer** [comment]
Weird, there should already be a little indicator popping up on the right side of the screen when reputation is gained/lost. I'll look into it

**Comment by TheComputerizer** [comment]
The rendering was redone for the indicator in 1.0.0 and it was made a little bigger so it should work in most if not all cases now. Feel free to open another issue if there are still problems
