### ISSUE TITLE
Currently the currancy bundles are not working in the modpack this was made for

### ISSUE THREAD

**Issue by Lavawulf** [AFunProject/Reputation#9]
The currency bundles in Dawncraft are not working, the signing them does not work, and interacting with a ledger block does nothing at all.  Several people have brought this up in the Dawncraft support server, myself included, but not a single bit of notice has been given to the people asking for help.  I am bringing this to notice here, for the mod seems to be broken, and is keeping people on servers from doing the quest-line in the Dawncraft modpack, which seems to be the entire point in the modpack, thus the goal of the modpack is invalid due to this system not working correctly and the quest-line being interrupted.   I implore you to at least let the community on the Discord know it is being looked into before this modpack becomes obsolete for a community understanding that it is just broken and the goals of it are not achievable.

**Comment by TheComputerizer** [comment]
I'm not sure about the Dawncraft specific stuff as I was not a part of the actual packdev process, but if it's not mentioned, you need to have a bundle in your main hand and an ink sac in your offhand when you right click the ledger book to sign it.

As for the ledger itself, I would need more information like which version of the mod the pack uses and whether it affects singleplayer, servers or both

**Comment by Lavawulf** [comment]
I will test this out, for it did not mention holding an inksac in any
descriptions/steps I found anywhere

**Comment by TheComputerizer** [comment]
1.0.0 has been released which refactored a bunch of internal stuff. If you are still having problems feel free to open another issue
